import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 * This class creates a View for Flight Addition and inserts
 */
public class FlightAdditionController extends javax.swing.JInternalFrame {

  /**
   * Creates new form FlightAdditionController
   */
  public FlightAdditionController() {
    initComponents();
    generateFlightID();
  }

  Connection con;
  PreparedStatement pst;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JButton closeButton;
  private javax.swing.JLabel flightIDLabel;
  private javax.swing.JLabel airlineNameLabel;
  private javax.swing.JLabel sourceLabel;
  private javax.swing.JLabel destinationLabel;
  private javax.swing.JLabel dateLabel;
  private javax.swing.JLabel departureTimeLabel;
  private javax.swing.JLabel arrivalTimeLabel;
  private javax.swing.JLabel flightChargeLabel;
  private javax.swing.JPanel jPanel1;
  
  private javax.swing.JTextField arrivalTimeInput;
  private com.toedter.calendar.JDateChooser dateInput;
  private javax.swing.JComboBox<String> destinationInput;
  private javax.swing.JTextField departureTimeInput;
  private javax.swing.JTextField flightChargeInput;
  private javax.swing.JLabel flightID;
  private javax.swing.JTextField airlineNameInput;
  private javax.swing.JComboBox<String> sourceInput;
  // End of variables declaration//GEN-END:variables

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    flightIDLabel = new javax.swing.JLabel();
    flightID = new javax.swing.JLabel();
    airlineNameLabel = new javax.swing.JLabel();
    sourceLabel = new javax.swing.JLabel();
    destinationLabel = new javax.swing.JLabel();
    airlineNameInput = new javax.swing.JTextField();
    dateLabel = new javax.swing.JLabel();
    dateInput = new com.toedter.calendar.JDateChooser();
    departureTimeLabel = new javax.swing.JLabel();
    departureTimeInput = new javax.swing.JTextField();
    arrivalTimeInput = new javax.swing.JTextField();
    arrivalTimeLabel = new javax.swing.JLabel();
    flightChargeLabel = new javax.swing.JLabel();
    flightChargeInput = new javax.swing.JTextField();
    addButton = new javax.swing.JButton();
    closeButton = new javax.swing.JButton();
    sourceInput = new javax.swing.JComboBox<>();
    destinationInput = new javax.swing.JComboBox<>();

    jPanel1.setBackground(new java.awt.Color(51, 51, 255));

    flightIDLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    flightIDLabel.setForeground(new java.awt.Color(255, 255, 255));
    flightIDLabel.setText("Flight ID");

    flightID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    flightID.setForeground(new java.awt.Color(255, 255, 0));

    airlineNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    airlineNameLabel.setForeground(new java.awt.Color(255, 255, 255));
    airlineNameLabel.setText("Airline Name");

    sourceLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    sourceLabel.setForeground(new java.awt.Color(255, 255, 255));
    sourceLabel.setText("Source");

    destinationLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    destinationLabel.setForeground(new java.awt.Color(255, 255, 255));
    destinationLabel.setText("Destination");

    dateLabel.setForeground(new java.awt.Color(255, 255, 255));
    dateLabel.setText("Date");

    departureTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
    departureTimeLabel.setText("Departure Time");

    arrivalTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
    arrivalTimeLabel.setText("Arrival Time");

    flightChargeLabel.setForeground(new java.awt.Color(255, 255, 255));
    flightChargeLabel.setText("Flight Charge");

    addButton.setText("Add");
    addButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addFlightActionPerformed(evt);
      }
    });

    closeButton.setText("Close");
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });

    sourceInput.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"India\t", "Srilanka", "Uk", "Usa", "Canada", "Chinna"}));

    destinationInput.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[]{"India\t", "Srilanka", "Uk", "Usa", "Canada", "Chinna"}));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout
                    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightIDLabel)
                            .addComponent(airlineNameLabel))
                        .addGroup(jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(flightID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(airlineNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sourceLabel)
                                .addComponent(destinationLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                    false)
                                .addComponent(sourceInput, 0, 136, Short.MAX_VALUE)
                                .addComponent(destinationInput, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                    Short.MAX_VALUE))))
                .addGap(103, 103, 103)
                .addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateLabel)
                                .addComponent(departureTimeLabel)
                                .addComponent(arrivalTimeLabel)
                                .addComponent(flightChargeLabel)
                            )
                            .addGap(62, 62, 62)
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                    false)
                                .addComponent(dateInput, javax.swing.GroupLayout.DEFAULT_SIZE, 174,
                                    Short.MAX_VALUE)
                                .addComponent(departureTimeInput)
                                .addComponent(arrivalTimeInput)
                                .addComponent(flightChargeInput))
                        )
                        )
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flightIDLabel)
                            .addComponent(flightID)
                            .addComponent(dateLabel))
                        .addComponent(dateInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(airlineNameLabel)
                        .addComponent(airlineNameInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(departureTimeLabel)
                        .addComponent(departureTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sourceLabel)
                        .addComponent(arrivalTimeInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arrivalTimeLabel)
                        .addComponent(sourceInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                            javax.swing.GroupLayout.DEFAULT_SIZE,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(destinationLabel)
                                .addComponent(destinationInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(flightChargeLabel)
                                .addComponent(flightChargeInput,
                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                    javax.swing.GroupLayout.DEFAULT_SIZE,
                                    javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93,
                    Short.MAX_VALUE)
                .addGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                            javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                    javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * This method automatically generates the next FlightID for the flight to be added
   */
  public void generateFlightID() {
    try {
      Class.forName("com.mysql.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "");
      Statement s = con.createStatement();
      ResultSet rs = s.executeQuery("select MAX(id) from flight");
      rs.next();
      rs.getString("MAX(id)");
      if (rs.getString("MAX(id)") == null) {
        flightID.setText("FO001");
      } else {
        long id = Long
            .parseLong(rs.getString("MAX(id)").substring(2, rs.getString("MAX(id)").length()));
        id++;
        flightID.setText("FO" + String.format("%03d", id));


      }


    } catch (ClassNotFoundException ex) {
      Logger.getLogger(CustomerCreationController.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(CustomerCreationController.class.getName()).log(Level.SEVERE, null, ex);
    }

  }

  /**
   * This method is called in the event of the Add button being pressed
   * by the user to add a new flight to the database.
   *
   * @param evt
   */
  private void addFlightActionPerformed(
      java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    String id = flightID.getText();
    String flightname = airlineNameInput.getText();

    String source = sourceInput.getSelectedItem().toString().trim();
    String depart = destinationInput.getSelectedItem().toString().trim();

    DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
    String date = da.format(dateInput.getDate());

    String departtime = departureTimeInput.getText();
    String arrtime = arrivalTimeInput.getText();
    String flightcharge = flightChargeInput.getText();

    try {
      Class.forName("com.mysql.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "");
      pst = con.prepareStatement(
          "insert into flight(id,flightname,source,depart,date,deptime,arrtime,flightcharge)values(?,?,?,?,?,?,?,?)");

      pst.setString(1, id);
      pst.setString(2, flightname);
      pst.setString(3, source);
      pst.setString(4, depart);
      pst.setString(5, date);
      pst.setString(6, departtime);
      pst.setString(7, arrtime);
      pst.setString(8, flightcharge);

      pst.executeUpdate();

      JOptionPane.showMessageDialog(null, "Flight Createdd.........");
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(FlightAdditionController.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
      Logger.getLogger(FlightAdditionController.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * Closes the Flight Addition window
   * @param evt
   */
  private void closeButtonActionPerformed(
      java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:

    this.hide();
  }//GEN-LAST:event_jButton2ActionPerformed
}
